<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net462;net8.0;net10.0</TargetFrameworks>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(MSBuildProjectName).xml</DocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ChainingAssertion-NUnit.Bin</PackageId>
    <Version>5.0.0</Version>
    <GeneratePackageOnBuild Condition=" '$(Configuration)' == 'Release' ">true</GeneratePackageOnBuild>
    <Title>Chaining Assertion for NUnit - Binary Edition</Title>
    <Product>ChainingAssertion</Product>
    <Authors>neuecc, J.Sakamoto</Authors>
    <Company>neuecc</Company>
    <Copyright>licensed under Microsoft Public License(Ms-PL)</Copyright>
    <RepositoryUrl>https://github.com/jsakamoto/ChainingAssertion/tree/bin-edition</RepositoryUrl>
    <PackageProjectUrl>https://github.com/jsakamoto/ChainingAssertion/tree/bin-edition</PackageProjectUrl>
    <PackageLicenseExpression>MS-PL</PackageLicenseExpression>
    <PackageTags>test unittest NUnit</PackageTags>
    <PackageOutputPath>../dist</PackageOutputPath>
    <Description>Method Chaining base UnitTesting Extension Methods and Dynamic Private Accessor for NUnit.</Description>
    <PackageReleaseNotes>(Please write the package release notes in "RELEASE-NOTES.txt")</PackageReleaseNotes>
    <PackageIcon>nupkg-icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">
    <PackageReference Include="Microsoft.CSharp" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.contents\nupkg-icon.png" Visible="false" Pack="true" PackagePath="/" />
    <None Include="..\README.md" Visible="false" Pack="true" PackagePath="/" />
  </ItemGroup>

  <Target Name="BuildPackageReleaseNotes" BeforeTargets="GenerateNuspec">
    <ReadLinesFromFile File="RELEASE-NOTES.txt">
      <Output TaskParameter="Lines" ItemName="ReleaseNoteLines" />
    </ReadLinesFromFile>
    <PropertyGroup>
      <PackageReleaseNotes>@(ReleaseNoteLines, '%0a')</PackageReleaseNotes>
      <PackageReleaseNotes>$([System.Text.RegularExpressions.Regex]::Match($(PackageReleaseNotes), "^(v\.[\d\.]+.+?)v\.[\d\.]+", System.Text.RegularExpressions.RegexOptions.Singleline).Groups[1].Value)</PackageReleaseNotes>
    </PropertyGroup>
  </Target>

  <Import Project="..\ChainingAssertion.Shared\ChainingAssertion.Shared.projitems" Label="Shared" />

</Project>
