<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(MSBuildProjectName).xml</DocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ChainingAssertion-NUnit.Bin</PackageId>
    <Version>1.8.1</Version>
    <GeneratePackageOnBuild Condition=" '$(Configuration)' == 'Release' ">true</GeneratePackageOnBuild>
    <Authors>neuecc, J.Sakamoto</Authors>
    <PackageProjectUrl>https://github.com/jsakamoto/ChainingAssertion/tree/bin-edition</PackageProjectUrl>
    <!--<PackageLicenseExpression>Ms-PL</PackageLicenseExpression>-->
    <PackageLicenseUrl>https://github.com/jsakamoto/ChainingAssertion/blob/bin-edition/LiCENSE</PackageLicenseUrl>
    <PackageTags>test unittest NUnit</PackageTags>
    <Title>Chaining Assertion for NUnit - Binary Edition</Title>
    <PackageTitle>Chaining Assertion for NUnit - Binary Edition</PackageTitle>
    <PackageOutputPath>../dist</PackageOutputPath>
    <Description>Method Chaining base UnitTesting Extension Methods and Dynamic Private Accessor for NUnit.</Description>
    <PackageReleaseNotes>(Please write the package release notes in "RELEASE-NOTES.txt")</PackageReleaseNotes>
    <PackageIcon>nupkg-icon.png</PackageIcon>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.6.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.contents\nupkg-icon.png" Visible="false" Pack="true" PackagePath="/" />
    <None Include="..\README.md" Visible="false" Pack="true" PackagePath="/" />
  </ItemGroup>

  <Target Name="BuildPackageReleaseNotes" BeforeTargets="GenerateNuspec">
    <ReadLinesFromFile File="RELEASE-NOTES.txt">
      <Output TaskParameter="Lines" ItemName="ReleaseNoteLines" />
    </ReadLinesFromFile>
    <PropertyGroup>
      <PackageReleaseNotes>@(ReleaseNoteLines, '%0a')</PackageReleaseNotes>
      <PackageReleaseNotes>$([System.Text.RegularExpressions.Regex]::Match($(PackageReleaseNotes), "^(v\.[\d\.]+.+?)v\.[\d\.]+", System.Text.RegularExpressions.RegexOptions.Singleline).Groups[1].Value)</PackageReleaseNotes>
    </PropertyGroup>
  </Target>

</Project>
