<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ChainingAssertion.Bin</PackageId>
    <Version>2.1.0</Version>
    <GeneratePackageOnBuild Condition=" '$(Configuration)' == 'Release' ">true</GeneratePackageOnBuild>
    <Title>Chaining Assertion for MSTest - Binary Edition</Title>
    <Product>ChainingAssertion</Product>
    <Authors>neuecc, J.Sakamoto</Authors>
    <Company>neuecc</Company>
    <Copyright>licensed under Microsoft Public License(Ms-PL)</Copyright>
    <PackageLicenseUrl>https://github.com/jsakamoto/ChainingAssertion/blob/bin-edition/LiCENSE</PackageLicenseUrl>
    <RepositoryUrl>https://github.com/jsakamoto/ChainingAssertion/tree/bin-edition</RepositoryUrl>
    <PackageProjectUrl>https://github.com/jsakamoto/ChainingAssertion/tree/bin-edition</PackageProjectUrl>
    <PackageTags>test unittest mstest</PackageTags>
    <PackageOutputPath>../dist</PackageOutputPath>
    <Description>[DEPRECATED] Please use the "ChainingAssertion-MSTest.Bin" package instead. Now, this package is a metadata-only package and just redirects to the "ChainingAssertion-MSTest.Bin". / Method Chaining base UnitTesting Extension Methods and Dynamic Private Accessor for MSTest.</Description>
    <PackageReleaseNotes>(Please write the package release notes in "../ChainingAssertion.MSTest/RELEASE-NOTES.txt")</PackageReleaseNotes>
    <PackageIcon>nupkg-icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\.contents\nupkg-icon.png" Visible="false" Pack="true" PackagePath="/" />
    <None Include="..\README.md" Visible="false" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ChainingAssertion-MSTest.Bin" Version="2.1.0" />
  </ItemGroup>

  <Target Name="BuildPackageReleaseNotes" BeforeTargets="GenerateNuspec">
    <ReadLinesFromFile File="../ChainingAssertion.MSTest/RELEASE-NOTES.txt">
      <Output TaskParameter="Lines" ItemName="ReleaseNoteLines" />
    </ReadLinesFromFile>
    <PropertyGroup>
      <PackageReleaseNotes>@(ReleaseNoteLines, '%0a')</PackageReleaseNotes>
      <PackageReleaseNotes>$([System.Text.RegularExpressions.Regex]::Match($(PackageReleaseNotes), "^(v\.[\d\.]+.+?)v\.[\d\.]+", System.Text.RegularExpressions.RegexOptions.Singleline).Groups[1].Value)</PackageReleaseNotes>
    </PropertyGroup>
  </Target>

</Project>
