name: tests for xUnit

on:
  push:
    branches:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.*

      # Perform unit tests
      - name: Perform unit tests
        run: dotnet test ChainingAssertion.xUnit.UnitTest -l "console;verbosity=normal" -v:q --nologo -f:net8.0
