name: tests for xUnit

on:
  push:
    branches:
      - "*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v7

      # Install .NET SDK
      - name: Install .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: |
            8.0.*
            10.0.*

      # Perform unit tests
      - name: Perform unit tests
        run: dotnet test --solution ChainingAssertion.xUnit-Bin.slnx --output detailed
